<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\THLauncher.Vendas.Application\THLauncher.Vendas.Application.csproj" />
    <ProjectReference Include="..\THLauncher.Vendas.Infrastructure\THLauncher.Vendas.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
