<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\THLauncher.Produtos.Application\THLauncher.Produtos.Application.csproj" />
    <ProjectReference Include="..\THLauncher.Produtos.Infrastructure\THLauncher.Produtos.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
